//! Embedded SVG icon assets.
//!
//! Provides an [`EmbeddedIconAssets`] implementation of [`gpui::AssetSource`]
//! that serves SVG icon data from compile-time `include_bytes!()` calls.

use std::borrow::Cow;
use std::collections::HashMap;
use std::sync::LazyLock;

use gpui::SharedString;

/// Color role for multi-color icon layers.
///
/// Each layer of a multi-color icon is tinted with a semantic color
/// from the theme, identified by this role.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum IconColorRole {
    /// Default/muted strokes — maps to `theme.text_muted`.
    Muted,
    /// Success/green — maps to `theme.success`.
    Success,
    /// Info/blue — maps to `theme.info`.
    Info,
    /// Warning/amber — maps to `theme.warning`.
    Warning,
    /// Error/red — maps to `theme.error`.
    Error,
    /// AI/purple — maps to `theme.ai`.
    Ai,
}

/// Rendering strategy for an icon.
#[derive(Debug, Clone)]
pub(crate) enum RenderStrategy {
    /// Single monochrome SVG, tinted with the caller's color.
    Monochrome(&'static str),
    /// Multiple SVG layers, each tinted with a semantic theme color.
    /// The caller's color overrides the `Muted` layer.
    MultiColor(&'static [(&'static str, IconColorRole)]),
}

/// Embedded icon asset source for GPUI.
///
/// Register this with your GPUI application to enable SVG icon rendering:
/// ```ignore
/// application().with_assets(EmbeddedIconAssets).run(|cx| { ... });
/// ```
pub struct EmbeddedIconAssets;

impl gpui::AssetSource for EmbeddedIconAssets {
    fn load(&self, path: &str) -> gpui::Result<Option<Cow<'static, [u8]>>> {
        Ok(lookup_svg(path).map(Cow::Borrowed))
    }

    fn list(&self, path: &str) -> gpui::Result<Vec<SharedString>> {
        Ok(ICON_ENTRIES
            .iter()
            .filter(|(p, _)| p.starts_with(path))
            .map(|(p, _)| SharedString::from(*p))
            .collect())
    }
}

/// O(1) lookup from icon path to embedded SVG bytes, built lazily on first use.
///
/// GPUI caches decoded SVGs after first load, so this map is only consulted
/// on cold paths. Using a `HashMap` keeps cold-path cost constant as the
/// icon set grows (currently ~380 entries).
static ICON_INDEX: LazyLock<HashMap<&'static str, &'static [u8]>> =
    LazyLock::new(|| ICON_ENTRIES.iter().copied().collect());

fn lookup_svg(path: &str) -> Option<&'static [u8]> {
    ICON_INDEX.get(path).copied()
}

/// All embedded SVG icon data.
static ICON_ENTRIES: &[(&str, &[u8])] = &[
    (
        "icons/ai-sdk/alert-triangle.svg",
        include_bytes!("../../../assets/icons/ai-sdk/alert-triangle.svg"),
    ),
    (
        "icons/ai-sdk/arrow-down.svg",
        include_bytes!("../../../assets/icons/ai-sdk/arrow-down.svg"),
    ),
    (
        "icons/ai-sdk/arrow-right.svg",
        include_bytes!("../../../assets/icons/ai-sdk/arrow-right.svg"),
    ),
    (
        "icons/ai-sdk/book.svg",
        include_bytes!("../../../assets/icons/ai-sdk/book.svg"),
    ),
    (
        "icons/ai-sdk/bookmark.svg",
        include_bytes!("../../../assets/icons/ai-sdk/bookmark.svg"),
    ),
    (
        "icons/ai-sdk/bot.svg",
        include_bytes!("../../../assets/icons/ai-sdk/bot.svg"),
    ),
    (
        "icons/ai-sdk/brain.svg",
        include_bytes!("../../../assets/icons/ai-sdk/brain.svg"),
    ),
    (
        "icons/ai-sdk/bug.svg",
        include_bytes!("../../../assets/icons/ai-sdk/bug.svg"),
    ),
    (
        "icons/ai-sdk/check.svg",
        include_bytes!("../../../assets/icons/ai-sdk/check.svg"),
    ),
    (
        "icons/ai-sdk/chevron-down.svg",
        include_bytes!("../../../assets/icons/ai-sdk/chevron-down.svg"),
    ),
    (
        "icons/ai-sdk/chevron-left.svg",
        include_bytes!("../../../assets/icons/ai-sdk/chevron-left.svg"),
    ),
    (
        "icons/ai-sdk/chevron-right.svg",
        include_bytes!("../../../assets/icons/ai-sdk/chevron-right.svg"),
    ),
    (
        "icons/ai-sdk/chevron-up.svg",
        include_bytes!("../../../assets/icons/ai-sdk/chevron-up.svg"),
    ),
    (
        "icons/ai-sdk/chevrons-up-down.svg",
        include_bytes!("../../../assets/icons/ai-sdk/chevrons-up-down.svg"),
    ),
    (
        "icons/ai-sdk/circle-filled.svg",
        include_bytes!("../../../assets/icons/ai-sdk/circle-filled.svg"),
    ),
    (
        "icons/ai-sdk/circle-outline.svg",
        include_bytes!("../../../assets/icons/ai-sdk/circle-outline.svg"),
    ),
    (
        "icons/ai-sdk/code.svg",
        include_bytes!("../../../assets/icons/ai-sdk/code.svg"),
    ),
    (
        "icons/ai-sdk/copy.svg",
        include_bytes!("../../../assets/icons/ai-sdk/copy.svg"),
    ),
    (
        "icons/ai-sdk/database.svg",
        include_bytes!("../../../assets/icons/ai-sdk/database.svg"),
    ),
    (
        "icons/ai-sdk/download.svg",
        include_bytes!("../../../assets/icons/ai-sdk/download.svg"),
    ),
    (
        "icons/ai-sdk/external-link.svg",
        include_bytes!("../../../assets/icons/ai-sdk/external-link.svg"),
    ),
    (
        "icons/ai-sdk/eye-off.svg",
        include_bytes!("../../../assets/icons/ai-sdk/eye-off.svg"),
    ),
    (
        "icons/ai-sdk/eye.svg",
        include_bytes!("../../../assets/icons/ai-sdk/eye.svg"),
    ),
    (
        "icons/ai-sdk/file-code.svg",
        include_bytes!("../../../assets/icons/ai-sdk/file-code.svg"),
    ),
    (
        "icons/ai-sdk/file.svg",
        include_bytes!("../../../assets/icons/ai-sdk/file.svg"),
    ),
    (
        "icons/ai-sdk/folder-open.svg",
        include_bytes!("../../../assets/icons/ai-sdk/folder-open.svg"),
    ),
    (
        "icons/ai-sdk/folder.svg",
        include_bytes!("../../../assets/icons/ai-sdk/folder.svg"),
    ),
    (
        "icons/ai-sdk/git-commit.svg",
        include_bytes!("../../../assets/icons/ai-sdk/git-commit.svg"),
    ),
    (
        "icons/ai-sdk/globe.svg",
        include_bytes!("../../../assets/icons/ai-sdk/globe.svg"),
    ),
    (
        "icons/ai-sdk/image.svg",
        include_bytes!("../../../assets/icons/ai-sdk/image.svg"),
    ),
    (
        "icons/ai-sdk/key.svg",
        include_bytes!("../../../assets/icons/ai-sdk/key.svg"),
    ),
    (
        "icons/ai-sdk/link.svg",
        include_bytes!("../../../assets/icons/ai-sdk/link.svg"),
    ),
    (
        "icons/ai-sdk/list-todo.svg",
        include_bytes!("../../../assets/icons/ai-sdk/list-todo.svg"),
    ),
    (
        "icons/ai-sdk/loader.svg",
        include_bytes!("../../../assets/icons/ai-sdk/loader.svg"),
    ),
    (
        "icons/ai-sdk/lock.svg",
        include_bytes!("../../../assets/icons/ai-sdk/lock.svg"),
    ),
    (
        "icons/ai-sdk/maximize.svg",
        include_bytes!("../../../assets/icons/ai-sdk/maximize.svg"),
    ),
    (
        "icons/ai-sdk/mic.svg",
        include_bytes!("../../../assets/icons/ai-sdk/mic.svg"),
    ),
    (
        "icons/ai-sdk/mic-off.svg",
        include_bytes!("../../../assets/icons/ai-sdk/mic-off.svg"),
    ),
    (
        "icons/ai-sdk/minus.svg",
        include_bytes!("../../../assets/icons/ai-sdk/minus.svg"),
    ),
    (
        "icons/ai-sdk/package.svg",
        include_bytes!("../../../assets/icons/ai-sdk/package.svg"),
    ),
    (
        "icons/ai-sdk/paperclip.svg",
        include_bytes!("../../../assets/icons/ai-sdk/paperclip.svg"),
    ),
    (
        "icons/ai-sdk/pause.svg",
        include_bytes!("../../../assets/icons/ai-sdk/pause.svg"),
    ),
    (
        "icons/ai-sdk/pencil.svg",
        include_bytes!("../../../assets/icons/ai-sdk/pencil.svg"),
    ),
    (
        "icons/ai-sdk/phone.svg",
        include_bytes!("../../../assets/icons/ai-sdk/phone.svg"),
    ),
    (
        "icons/ai-sdk/play.svg",
        include_bytes!("../../../assets/icons/ai-sdk/play.svg"),
    ),
    (
        "icons/ai-sdk/plus.svg",
        include_bytes!("../../../assets/icons/ai-sdk/plus.svg"),
    ),
    (
        "icons/ai-sdk/rotate-ccw.svg",
        include_bytes!("../../../assets/icons/ai-sdk/rotate-ccw.svg"),
    ),
    (
        "icons/ai-sdk/search.svg",
        include_bytes!("../../../assets/icons/ai-sdk/search.svg"),
    ),
    (
        "icons/ai-sdk/send.svg",
        include_bytes!("../../../assets/icons/ai-sdk/send.svg"),
    ),
    (
        "icons/ai-sdk/settings.svg",
        include_bytes!("../../../assets/icons/ai-sdk/settings.svg"),
    ),
    (
        "icons/ai-sdk/share.svg",
        include_bytes!("../../../assets/icons/ai-sdk/share.svg"),
    ),
    (
        "icons/ai-sdk/skip-back.svg",
        include_bytes!("../../../assets/icons/ai-sdk/skip-back.svg"),
    ),
    (
        "icons/ai-sdk/skip-forward.svg",
        include_bytes!("../../../assets/icons/ai-sdk/skip-forward.svg"),
    ),
    (
        "icons/ai-sdk/sparkle.svg",
        include_bytes!("../../../assets/icons/ai-sdk/sparkle.svg"),
    ),
    (
        "icons/ai-sdk/square.svg",
        include_bytes!("../../../assets/icons/ai-sdk/square.svg"),
    ),
    (
        "icons/ai-sdk/terminal.svg",
        include_bytes!("../../../assets/icons/ai-sdk/terminal.svg"),
    ),
    (
        "icons/ai-sdk/test-tube.svg",
        include_bytes!("../../../assets/icons/ai-sdk/test-tube.svg"),
    ),
    (
        "icons/ai-sdk/thumbs-down.svg",
        include_bytes!("../../../assets/icons/ai-sdk/thumbs-down.svg"),
    ),
    (
        "icons/ai-sdk/thumbs-up.svg",
        include_bytes!("../../../assets/icons/ai-sdk/thumbs-up.svg"),
    ),
    (
        "icons/ai-sdk/trash.svg",
        include_bytes!("../../../assets/icons/ai-sdk/trash.svg"),
    ),
    (
        "icons/ai-sdk/unlock.svg",
        include_bytes!("../../../assets/icons/ai-sdk/unlock.svg"),
    ),
    (
        "icons/ai-sdk/video.svg",
        include_bytes!("../../../assets/icons/ai-sdk/video.svg"),
    ),
    (
        "icons/ai-sdk/volume-x.svg",
        include_bytes!("../../../assets/icons/ai-sdk/volume-x.svg"),
    ),
    (
        "icons/ai-sdk/volume2.svg",
        include_bytes!("../../../assets/icons/ai-sdk/volume2.svg"),
    ),
    (
        "icons/ai-sdk/x.svg",
        include_bytes!("../../../assets/icons/ai-sdk/x.svg"),
    ),
    (
        "icons/languages/bash.svg",
        include_bytes!("../../../assets/icons/languages/bash.svg"),
    ),
    (
        "icons/languages/c.svg",
        include_bytes!("../../../assets/icons/languages/c.svg"),
    ),
    (
        "icons/languages/cpp.svg",
        include_bytes!("../../../assets/icons/languages/cpp.svg"),
    ),
    (
        "icons/languages/css.svg",
        include_bytes!("../../../assets/icons/languages/css.svg"),
    ),
    (
        "icons/languages/go.svg",
        include_bytes!("../../../assets/icons/languages/go.svg"),
    ),
    (
        "icons/languages/html.svg",
        include_bytes!("../../../assets/icons/languages/html.svg"),
    ),
    (
        "icons/languages/javascript.svg",
        include_bytes!("../../../assets/icons/languages/javascript.svg"),
    ),
    (
        "icons/languages/json.svg",
        include_bytes!("../../../assets/icons/languages/json.svg"),
    ),
    (
        "icons/languages/python.svg",
        include_bytes!("../../../assets/icons/languages/python.svg"),
    ),
    (
        "icons/languages/rust.svg",
        include_bytes!("../../../assets/icons/languages/rust.svg"),
    ),
    (
        "icons/languages/toml.svg",
        include_bytes!("../../../assets/icons/languages/toml.svg"),
    ),
    (
        "icons/languages/typescript.svg",
        include_bytes!("../../../assets/icons/languages/typescript.svg"),
    ),
    (
        "icons/providers/claude.svg",
        include_bytes!("../../../assets/icons/providers/claude.svg"),
    ),
    (
        "icons/providers/cohere.svg",
        include_bytes!("../../../assets/icons/providers/cohere.svg"),
    ),
    (
        "icons/providers/custom.svg",
        include_bytes!("../../../assets/icons/providers/custom.svg"),
    ),
    (
        "icons/providers/deepseek.svg",
        include_bytes!("../../../assets/icons/providers/deepseek.svg"),
    ),
    (
        "icons/providers/ernie.svg",
        include_bytes!("../../../assets/icons/providers/ernie.svg"),
    ),
    (
        "icons/providers/gemini.svg",
        include_bytes!("../../../assets/icons/providers/gemini.svg"),
    ),
    (
        "icons/providers/gemma.svg",
        include_bytes!("../../../assets/icons/providers/gemma.svg"),
    ),
    (
        "icons/providers/glm.svg",
        include_bytes!("../../../assets/icons/providers/glm.svg"),
    ),
    (
        "icons/providers/gpt.svg",
        include_bytes!("../../../assets/icons/providers/gpt.svg"),
    ),
    (
        "icons/providers/grok.svg",
        include_bytes!("../../../assets/icons/providers/grok.svg"),
    ),
    (
        "icons/providers/llama.svg",
        include_bytes!("../../../assets/icons/providers/llama.svg"),
    ),
    (
        "icons/providers/minimax.svg",
        include_bytes!("../../../assets/icons/providers/minimax.svg"),
    ),
    (
        "icons/providers/mistral.svg",
        include_bytes!("../../../assets/icons/providers/mistral.svg"),
    ),
    (
        "icons/providers/nova.svg",
        include_bytes!("../../../assets/icons/providers/nova.svg"),
    ),
    (
        "icons/providers/perplexity.svg",
        include_bytes!("../../../assets/icons/providers/perplexity.svg"),
    ),
    (
        "icons/providers/phi.svg",
        include_bytes!("../../../assets/icons/providers/phi.svg"),
    ),
    (
        "icons/providers/qwen.svg",
        include_bytes!("../../../assets/icons/providers/qwen.svg"),
    ),
    (
        "icons/git/added_success.svg",
        include_bytes!("../../../assets/icons/git/added_success.svg"),
    ),
    (
        "icons/git/ahead_info.svg",
        include_bytes!("../../../assets/icons/git/ahead_info.svg"),
    ),
    (
        "icons/git/behind_warning.svg",
        include_bytes!("../../../assets/icons/git/behind_warning.svg"),
    ),
    (
        "icons/git/blame_muted.svg",
        include_bytes!("../../../assets/icons/git/blame_muted.svg"),
    ),
    (
        "icons/git/blame_warning.svg",
        include_bytes!("../../../assets/icons/git/blame_warning.svg"),
    ),
    (
        "icons/git/branch_muted.svg",
        include_bytes!("../../../assets/icons/git/branch_muted.svg"),
    ),
    (
        "icons/git/checkout_muted.svg",
        include_bytes!("../../../assets/icons/git/checkout_muted.svg"),
    ),
    (
        "icons/git/clean_success.svg",
        include_bytes!("../../../assets/icons/git/clean_success.svg"),
    ),
    (
        "icons/git/clone_muted.svg",
        include_bytes!("../../../assets/icons/git/clone_muted.svg"),
    ),
    (
        "icons/git/code-review_info.svg",
        include_bytes!("../../../assets/icons/git/code-review_info.svg"),
    ),
    (
        "icons/git/code-review_muted.svg",
        include_bytes!("../../../assets/icons/git/code-review_muted.svg"),
    ),
    (
        "icons/git/commit_muted.svg",
        include_bytes!("../../../assets/icons/git/commit_muted.svg"),
    ),
    (
        "icons/git/compare_error.svg",
        include_bytes!("../../../assets/icons/git/compare_error.svg"),
    ),
    (
        "icons/git/compare_muted.svg",
        include_bytes!("../../../assets/icons/git/compare_muted.svg"),
    ),
    (
        "icons/git/compare_success.svg",
        include_bytes!("../../../assets/icons/git/compare_success.svg"),
    ),
    (
        "icons/git/conflict_warning.svg",
        include_bytes!("../../../assets/icons/git/conflict_warning.svg"),
    ),
    (
        "icons/git/deleted_error.svg",
        include_bytes!("../../../assets/icons/git/deleted_error.svg"),
    ),
    (
        "icons/git/fork_muted.svg",
        include_bytes!("../../../assets/icons/git/fork_muted.svg"),
    ),
    (
        "icons/git/ignored_muted.svg",
        include_bytes!("../../../assets/icons/git/ignored_muted.svg"),
    ),
    (
        "icons/git/inline-diff_error.svg",
        include_bytes!("../../../assets/icons/git/inline-diff_error.svg"),
    ),
    (
        "icons/git/inline-diff_muted.svg",
        include_bytes!("../../../assets/icons/git/inline-diff_muted.svg"),
    ),
    (
        "icons/git/inline-diff_success.svg",
        include_bytes!("../../../assets/icons/git/inline-diff_success.svg"),
    ),
    (
        "icons/git/log_muted.svg",
        include_bytes!("../../../assets/icons/git/log_muted.svg"),
    ),
    (
        "icons/git/merge_success.svg",
        include_bytes!("../../../assets/icons/git/merge_success.svg"),
    ),
    (
        "icons/git/modified_warning.svg",
        include_bytes!("../../../assets/icons/git/modified_warning.svg"),
    ),
    (
        "icons/git/pull-request_success.svg",
        include_bytes!("../../../assets/icons/git/pull-request_success.svg"),
    ),
    (
        "icons/git/pull_info.svg",
        include_bytes!("../../../assets/icons/git/pull_info.svg"),
    ),
    (
        "icons/git/push_success.svg",
        include_bytes!("../../../assets/icons/git/push_success.svg"),
    ),
    (
        "icons/git/rebase_ai.svg",
        include_bytes!("../../../assets/icons/git/rebase_ai.svg"),
    ),
    (
        "icons/git/rebase_muted.svg",
        include_bytes!("../../../assets/icons/git/rebase_muted.svg"),
    ),
    (
        "icons/git/remote_muted.svg",
        include_bytes!("../../../assets/icons/git/remote_muted.svg"),
    ),
    (
        "icons/git/staged_success.svg",
        include_bytes!("../../../assets/icons/git/staged_success.svg"),
    ),
    (
        "icons/git/staging_muted.svg",
        include_bytes!("../../../assets/icons/git/staging_muted.svg"),
    ),
    (
        "icons/git/staging_success.svg",
        include_bytes!("../../../assets/icons/git/staging_success.svg"),
    ),
    (
        "icons/git/stash_muted.svg",
        include_bytes!("../../../assets/icons/git/stash_muted.svg"),
    ),
    (
        "icons/git/tag_muted.svg",
        include_bytes!("../../../assets/icons/git/tag_muted.svg"),
    ),
    (
        "icons/git/untracked_muted.svg",
        include_bytes!("../../../assets/icons/git/untracked_muted.svg"),
    ),
    (
        "icons/dev-tools/agent_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/agent_ai.svg"),
    ),
    (
        "icons/dev-tools/api_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/api_info.svg"),
    ),
    (
        "icons/dev-tools/breadcrumb_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/breadcrumb_info.svg"),
    ),
    (
        "icons/dev-tools/breadcrumb_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/breadcrumb_muted.svg"),
    ),
    (
        "icons/dev-tools/cache_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/cache_warning.svg"),
    ),
    (
        "icons/dev-tools/chain_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/chain_ai.svg"),
    ),
    (
        "icons/dev-tools/ci-cd_success.svg",
        include_bytes!("../../../assets/icons/dev-tools/ci-cd_success.svg"),
    ),
    (
        "icons/dev-tools/container_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/container_info.svg"),
    ),
    (
        "icons/dev-tools/context_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/context_ai.svg"),
    ),
    (
        "icons/dev-tools/debug_error.svg",
        include_bytes!("../../../assets/icons/dev-tools/debug_error.svg"),
    ),
    (
        "icons/dev-tools/deploy_success.svg",
        include_bytes!("../../../assets/icons/dev-tools/deploy_success.svg"),
    ),
    (
        "icons/dev-tools/embedding_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/embedding_ai.svg"),
    ),
    (
        "icons/dev-tools/environment_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/environment_info.svg"),
    ),
    (
        "icons/dev-tools/environment_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/environment_muted.svg"),
    ),
    (
        "icons/dev-tools/extension_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/extension_ai.svg"),
    ),
    (
        "icons/dev-tools/file_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/file_muted.svg"),
    ),
    (
        "icons/dev-tools/find-replace_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/find-replace_info.svg"),
    ),
    (
        "icons/dev-tools/fine-tune_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/fine-tune_warning.svg"),
    ),
    (
        "icons/dev-tools/folder_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/folder_muted.svg"),
    ),
    (
        "icons/dev-tools/function-call_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/function-call_muted.svg"),
    ),
    (
        "icons/dev-tools/function-call_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/function-call_warning.svg"),
    ),
    (
        "icons/dev-tools/guardrail_success.svg",
        include_bytes!("../../../assets/icons/dev-tools/guardrail_success.svg"),
    ),
    (
        "icons/dev-tools/health_error.svg",
        include_bytes!("../../../assets/icons/dev-tools/health_error.svg"),
    ),
    (
        "icons/dev-tools/keyboard_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/keyboard_muted.svg"),
    ),
    (
        "icons/dev-tools/logs_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/logs_muted.svg"),
    ),
    (
        "icons/dev-tools/logs_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/logs_warning.svg"),
    ),
    (
        "icons/dev-tools/memory_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/memory_ai.svg"),
    ),
    (
        "icons/dev-tools/minimap_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/minimap_info.svg"),
    ),
    (
        "icons/dev-tools/minimap_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/minimap_muted.svg"),
    ),
    (
        "icons/dev-tools/model_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/model_ai.svg"),
    ),
    (
        "icons/dev-tools/monitor_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/monitor_muted.svg"),
    ),
    (
        "icons/dev-tools/monitor_success.svg",
        include_bytes!("../../../assets/icons/dev-tools/monitor_success.svg"),
    ),
    (
        "icons/dev-tools/orchestrator_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/orchestrator_ai.svg"),
    ),
    (
        "icons/dev-tools/orchestrator_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/orchestrator_muted.svg"),
    ),
    (
        "icons/dev-tools/palette_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/palette_info.svg"),
    ),
    (
        "icons/dev-tools/palette_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/palette_muted.svg"),
    ),
    (
        "icons/dev-tools/pipeline_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/pipeline_muted.svg"),
    ),
    (
        "icons/dev-tools/pipeline_success.svg",
        include_bytes!("../../../assets/icons/dev-tools/pipeline_success.svg"),
    ),
    (
        "icons/dev-tools/pipeline_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/pipeline_warning.svg"),
    ),
    (
        "icons/dev-tools/prompt_ai.svg",
        include_bytes!("../../../assets/icons/dev-tools/prompt_ai.svg"),
    ),
    (
        "icons/dev-tools/queue_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/queue_muted.svg"),
    ),
    (
        "icons/dev-tools/rag_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/rag_info.svg"),
    ),
    (
        "icons/dev-tools/rag_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/rag_muted.svg"),
    ),
    (
        "icons/dev-tools/rollback_error.svg",
        include_bytes!("../../../assets/icons/dev-tools/rollback_error.svg"),
    ),
    (
        "icons/dev-tools/scale_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/scale_muted.svg"),
    ),
    (
        "icons/dev-tools/scale_success.svg",
        include_bytes!("../../../assets/icons/dev-tools/scale_success.svg"),
    ),
    (
        "icons/dev-tools/search_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/search_info.svg"),
    ),
    (
        "icons/dev-tools/secret_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/secret_warning.svg"),
    ),
    (
        "icons/dev-tools/settings_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/settings_muted.svg"),
    ),
    (
        "icons/dev-tools/sidebar_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/sidebar_muted.svg"),
    ),
    (
        "icons/dev-tools/snippet_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/snippet_muted.svg"),
    ),
    (
        "icons/dev-tools/snippet_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/snippet_warning.svg"),
    ),
    (
        "icons/dev-tools/split-view_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/split-view_muted.svg"),
    ),
    (
        "icons/dev-tools/streaming_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/streaming_info.svg"),
    ),
    (
        "icons/dev-tools/tab_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/tab_muted.svg"),
    ),
    (
        "icons/dev-tools/terminal_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/terminal_muted.svg"),
    ),
    (
        "icons/dev-tools/terminal_success.svg",
        include_bytes!("../../../assets/icons/dev-tools/terminal_success.svg"),
    ),
    (
        "icons/dev-tools/token_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/token_warning.svg"),
    ),
    (
        "icons/dev-tools/tool-use_warning.svg",
        include_bytes!("../../../assets/icons/dev-tools/tool-use_warning.svg"),
    ),
    (
        "icons/dev-tools/webhook_info.svg",
        include_bytes!("../../../assets/icons/dev-tools/webhook_info.svg"),
    ),
    (
        "icons/dev-tools/webhook_muted.svg",
        include_bytes!("../../../assets/icons/dev-tools/webhook_muted.svg"),
    ),
    // SF Symbols 7 glyphs — extracted from the canonical template SVGs via
    // `scripts/extract_sf_symbol.py`. These carry dot-notation filenames
    // matching Apple's identifiers so future native-path integrations
    // (`NSImage(systemSymbolName:)`) can use the same strings.
    (
        "icons/sf/ant.svg",
        include_bytes!("../../../assets/icons/sf/ant.svg"),
    ),
    (
        "icons/sf/apple.terminal.svg",
        include_bytes!("../../../assets/icons/sf/apple.terminal.svg"),
    ),
    (
        "icons/sf/arrow.clockwise.svg",
        include_bytes!("../../../assets/icons/sf/arrow.clockwise.svg"),
    ),
    (
        "icons/sf/arrow.down.circle.svg",
        include_bytes!("../../../assets/icons/sf/arrow.down.circle.svg"),
    ),
    (
        "icons/sf/arrow.down.svg",
        include_bytes!("../../../assets/icons/sf/arrow.down.svg"),
    ),
    (
        "icons/sf/arrow.right.svg",
        include_bytes!("../../../assets/icons/sf/arrow.right.svg"),
    ),
    (
        "icons/sf/arrowtriangle.down.fill.svg",
        include_bytes!("../../../assets/icons/sf/arrowtriangle.down.fill.svg"),
    ),
    (
        "icons/sf/arrowtriangle.right.fill.svg",
        include_bytes!("../../../assets/icons/sf/arrowtriangle.right.fill.svg"),
    ),
    (
        "icons/sf/arrow.up.left.and.arrow.down.right.svg",
        include_bytes!("../../../assets/icons/sf/arrow.up.left.and.arrow.down.right.svg"),
    ),
    (
        "icons/sf/arrow.up.right.square.svg",
        include_bytes!("../../../assets/icons/sf/arrow.up.right.square.svg"),
    ),
    (
        "icons/sf/arrow.uturn.backward.svg",
        include_bytes!("../../../assets/icons/sf/arrow.uturn.backward.svg"),
    ),
    (
        "icons/sf/arrow.uturn.forward.svg",
        include_bytes!("../../../assets/icons/sf/arrow.uturn.forward.svg"),
    ),
    (
        "icons/sf/backward.end.svg",
        include_bytes!("../../../assets/icons/sf/backward.end.svg"),
    ),
    (
        "icons/sf/book.svg",
        include_bytes!("../../../assets/icons/sf/book.svg"),
    ),
    (
        "icons/sf/bookmark.svg",
        include_bytes!("../../../assets/icons/sf/bookmark.svg"),
    ),
    (
        "icons/sf/brain.svg",
        include_bytes!("../../../assets/icons/sf/brain.svg"),
    ),
    (
        "icons/sf/checklist.svg",
        include_bytes!("../../../assets/icons/sf/checklist.svg"),
    ),
    (
        "icons/sf/checkmark.svg",
        include_bytes!("../../../assets/icons/sf/checkmark.svg"),
    ),
    (
        "icons/sf/chevron.down.svg",
        include_bytes!("../../../assets/icons/sf/chevron.down.svg"),
    ),
    (
        "icons/sf/chevron.left.forwardslash.chevron.right.svg",
        include_bytes!("../../../assets/icons/sf/chevron.left.forwardslash.chevron.right.svg"),
    ),
    (
        "icons/sf/chevron.left.svg",
        include_bytes!("../../../assets/icons/sf/chevron.left.svg"),
    ),
    (
        "icons/sf/chevron.right.svg",
        include_bytes!("../../../assets/icons/sf/chevron.right.svg"),
    ),
    (
        "icons/sf/chevron.up.chevron.down.svg",
        include_bytes!("../../../assets/icons/sf/chevron.up.chevron.down.svg"),
    ),
    (
        "icons/sf/chevron.up.svg",
        include_bytes!("../../../assets/icons/sf/chevron.up.svg"),
    ),
    (
        "icons/sf/circle.fill.svg",
        include_bytes!("../../../assets/icons/sf/circle.fill.svg"),
    ),
    (
        "icons/sf/circle.svg",
        include_bytes!("../../../assets/icons/sf/circle.svg"),
    ),
    (
        "icons/sf/cylinder.svg",
        include_bytes!("../../../assets/icons/sf/cylinder.svg"),
    ),
    (
        "icons/sf/document.on.document.svg",
        include_bytes!("../../../assets/icons/sf/document.on.document.svg"),
    ),
    (
        "icons/sf/document.svg",
        include_bytes!("../../../assets/icons/sf/document.svg"),
    ),
    (
        "icons/sf/exclamationmark.triangle.svg",
        include_bytes!("../../../assets/icons/sf/exclamationmark.triangle.svg"),
    ),
    (
        "icons/sf/eye.slash.svg",
        include_bytes!("../../../assets/icons/sf/eye.slash.svg"),
    ),
    (
        "icons/sf/eye.svg",
        include_bytes!("../../../assets/icons/sf/eye.svg"),
    ),
    (
        "icons/sf/film.svg",
        include_bytes!("../../../assets/icons/sf/film.svg"),
    ),
    (
        "icons/sf/folder.fill.svg",
        include_bytes!("../../../assets/icons/sf/folder.fill.svg"),
    ),
    (
        "icons/sf/folder.svg",
        include_bytes!("../../../assets/icons/sf/folder.svg"),
    ),
    (
        "icons/sf/forward.end.svg",
        include_bytes!("../../../assets/icons/sf/forward.end.svg"),
    ),
    (
        "icons/sf/gear.svg",
        include_bytes!("../../../assets/icons/sf/gear.svg"),
    ),
    (
        "icons/sf/globe.svg",
        include_bytes!("../../../assets/icons/sf/globe.svg"),
    ),
    (
        "icons/sf/hand.thumbsdown.svg",
        include_bytes!("../../../assets/icons/sf/hand.thumbsdown.svg"),
    ),
    (
        "icons/sf/hand.thumbsup.svg",
        include_bytes!("../../../assets/icons/sf/hand.thumbsup.svg"),
    ),
    (
        "icons/sf/key.svg",
        include_bytes!("../../../assets/icons/sf/key.svg"),
    ),
    (
        "icons/sf/link.svg",
        include_bytes!("../../../assets/icons/sf/link.svg"),
    ),
    (
        "icons/sf/lock.open.svg",
        include_bytes!("../../../assets/icons/sf/lock.open.svg"),
    ),
    (
        "icons/sf/lock.svg",
        include_bytes!("../../../assets/icons/sf/lock.svg"),
    ),
    (
        "icons/sf/magnifyingglass.svg",
        include_bytes!("../../../assets/icons/sf/magnifyingglass.svg"),
    ),
    (
        "icons/sf/microphone.svg",
        include_bytes!("../../../assets/icons/sf/microphone.svg"),
    ),
    (
        "icons/sf/microphone.slash.svg",
        include_bytes!("../../../assets/icons/sf/microphone.slash.svg"),
    ),
    (
        "icons/sf/minus.svg",
        include_bytes!("../../../assets/icons/sf/minus.svg"),
    ),
    (
        "icons/sf/paperclip.svg",
        include_bytes!("../../../assets/icons/sf/paperclip.svg"),
    ),
    (
        "icons/sf/paperplane.svg",
        include_bytes!("../../../assets/icons/sf/paperplane.svg"),
    ),
    (
        "icons/sf/pause.fill.svg",
        include_bytes!("../../../assets/icons/sf/pause.fill.svg"),
    ),
    (
        "icons/sf/pencil.svg",
        include_bytes!("../../../assets/icons/sf/pencil.svg"),
    ),
    (
        "icons/sf/phone.svg",
        include_bytes!("../../../assets/icons/sf/phone.svg"),
    ),
    (
        "icons/sf/photo.svg",
        include_bytes!("../../../assets/icons/sf/photo.svg"),
    ),
    (
        "icons/sf/play.fill.svg",
        include_bytes!("../../../assets/icons/sf/play.fill.svg"),
    ),
    (
        "icons/sf/progress.indicator.svg",
        include_bytes!("../../../assets/icons/sf/progress.indicator.svg"),
    ),
    (
        "icons/sf/plus.svg",
        include_bytes!("../../../assets/icons/sf/plus.svg"),
    ),
    (
        "icons/sf/shippingbox.svg",
        include_bytes!("../../../assets/icons/sf/shippingbox.svg"),
    ),
    (
        "icons/sf/sparkles.svg",
        include_bytes!("../../../assets/icons/sf/sparkles.svg"),
    ),
    (
        "icons/sf/speaker.slash.svg",
        include_bytes!("../../../assets/icons/sf/speaker.slash.svg"),
    ),
    (
        "icons/sf/speaker.wave.2.svg",
        include_bytes!("../../../assets/icons/sf/speaker.wave.2.svg"),
    ),
    (
        "icons/sf/square.and.arrow.up.svg",
        include_bytes!("../../../assets/icons/sf/square.and.arrow.up.svg"),
    ),
    (
        "icons/sf/square.svg",
        include_bytes!("../../../assets/icons/sf/square.svg"),
    ),
    (
        "icons/sf/star.fill.svg",
        include_bytes!("../../../assets/icons/sf/star.fill.svg"),
    ),
    (
        "icons/sf/star.leadinghalf.filled.svg",
        include_bytes!("../../../assets/icons/sf/star.leadinghalf.filled.svg"),
    ),
    (
        "icons/sf/star.svg",
        include_bytes!("../../../assets/icons/sf/star.svg"),
    ),
    (
        "icons/sf/testtube.2.svg",
        include_bytes!("../../../assets/icons/sf/testtube.2.svg"),
    ),
    (
        "icons/sf/trash.svg",
        include_bytes!("../../../assets/icons/sf/trash.svg"),
    ),
    (
        "icons/sf/xmark.svg",
        include_bytes!("../../../assets/icons/sf/xmark.svg"),
    ),
    // Liquid Glass variants (stroke-width 1.5)
    (
        "icons-glass/ai-sdk/alert-triangle.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/alert-triangle.svg"),
    ),
    (
        "icons-glass/ai-sdk/arrow-down.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/arrow-down.svg"),
    ),
    (
        "icons-glass/ai-sdk/arrow-right.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/arrow-right.svg"),
    ),
    (
        "icons-glass/ai-sdk/book.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/book.svg"),
    ),
    (
        "icons-glass/ai-sdk/bookmark.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/bookmark.svg"),
    ),
    (
        "icons-glass/ai-sdk/bot.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/bot.svg"),
    ),
    (
        "icons-glass/ai-sdk/brain.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/brain.svg"),
    ),
    (
        "icons-glass/ai-sdk/bug.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/bug.svg"),
    ),
    (
        "icons-glass/ai-sdk/check.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/check.svg"),
    ),
    (
        "icons-glass/ai-sdk/chevron-down.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/chevron-down.svg"),
    ),
    (
        "icons-glass/ai-sdk/chevron-left.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/chevron-left.svg"),
    ),
    (
        "icons-glass/ai-sdk/chevron-right.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/chevron-right.svg"),
    ),
    (
        "icons-glass/ai-sdk/chevron-up.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/chevron-up.svg"),
    ),
    (
        "icons-glass/ai-sdk/chevrons-up-down.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/chevrons-up-down.svg"),
    ),
    (
        "icons-glass/ai-sdk/circle-filled.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/circle-filled.svg"),
    ),
    (
        "icons-glass/ai-sdk/circle-outline.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/circle-outline.svg"),
    ),
    (
        "icons-glass/ai-sdk/code.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/code.svg"),
    ),
    (
        "icons-glass/ai-sdk/copy.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/copy.svg"),
    ),
    (
        "icons-glass/ai-sdk/database.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/database.svg"),
    ),
    (
        "icons-glass/ai-sdk/download.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/download.svg"),
    ),
    (
        "icons-glass/ai-sdk/external-link.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/external-link.svg"),
    ),
    (
        "icons-glass/ai-sdk/eye-off.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/eye-off.svg"),
    ),
    (
        "icons-glass/ai-sdk/eye.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/eye.svg"),
    ),
    (
        "icons-glass/ai-sdk/file-code.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/file-code.svg"),
    ),
    (
        "icons-glass/ai-sdk/file.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/file.svg"),
    ),
    (
        "icons-glass/ai-sdk/folder-open.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/folder-open.svg"),
    ),
    (
        "icons-glass/ai-sdk/folder.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/folder.svg"),
    ),
    (
        "icons-glass/ai-sdk/git-commit.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/git-commit.svg"),
    ),
    (
        "icons-glass/ai-sdk/globe.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/globe.svg"),
    ),
    (
        "icons-glass/ai-sdk/image.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/image.svg"),
    ),
    (
        "icons-glass/ai-sdk/key.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/key.svg"),
    ),
    (
        "icons-glass/ai-sdk/link.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/link.svg"),
    ),
    (
        "icons-glass/ai-sdk/list-todo.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/list-todo.svg"),
    ),
    (
        "icons-glass/ai-sdk/loader.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/loader.svg"),
    ),
    (
        "icons-glass/ai-sdk/lock.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/lock.svg"),
    ),
    (
        "icons-glass/ai-sdk/maximize.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/maximize.svg"),
    ),
    (
        "icons-glass/ai-sdk/mic.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/mic.svg"),
    ),
    (
        "icons-glass/ai-sdk/mic-off.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/mic-off.svg"),
    ),
    (
        "icons-glass/ai-sdk/minus.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/minus.svg"),
    ),
    (
        "icons-glass/ai-sdk/package.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/package.svg"),
    ),
    (
        "icons-glass/ai-sdk/paperclip.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/paperclip.svg"),
    ),
    (
        "icons-glass/ai-sdk/pause.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/pause.svg"),
    ),
    (
        "icons-glass/ai-sdk/pencil.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/pencil.svg"),
    ),
    (
        "icons-glass/ai-sdk/phone.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/phone.svg"),
    ),
    (
        "icons-glass/ai-sdk/play.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/play.svg"),
    ),
    (
        "icons-glass/ai-sdk/plus.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/plus.svg"),
    ),
    (
        "icons-glass/ai-sdk/progress-spinner.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/progress-spinner.svg"),
    ),
    (
        "icons-glass/ai-sdk/rotate-ccw.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/rotate-ccw.svg"),
    ),
    (
        "icons-glass/ai-sdk/search.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/search.svg"),
    ),
    (
        "icons-glass/ai-sdk/send.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/send.svg"),
    ),
    (
        "icons-glass/ai-sdk/settings.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/settings.svg"),
    ),
    (
        "icons-glass/ai-sdk/share.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/share.svg"),
    ),
    (
        "icons-glass/ai-sdk/skip-back.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/skip-back.svg"),
    ),
    (
        "icons-glass/ai-sdk/skip-forward.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/skip-forward.svg"),
    ),
    (
        "icons-glass/ai-sdk/sparkle.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/sparkle.svg"),
    ),
    (
        "icons-glass/ai-sdk/square.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/square.svg"),
    ),
    (
        "icons-glass/ai-sdk/terminal.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/terminal.svg"),
    ),
    (
        "icons-glass/ai-sdk/test-tube.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/test-tube.svg"),
    ),
    (
        "icons-glass/ai-sdk/thumbs-down.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/thumbs-down.svg"),
    ),
    (
        "icons-glass/ai-sdk/thumbs-up.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/thumbs-up.svg"),
    ),
    (
        "icons-glass/ai-sdk/trash.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/trash.svg"),
    ),
    (
        "icons-glass/ai-sdk/unlock.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/unlock.svg"),
    ),
    (
        "icons-glass/ai-sdk/video.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/video.svg"),
    ),
    (
        "icons-glass/ai-sdk/volume-x.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/volume-x.svg"),
    ),
    (
        "icons-glass/ai-sdk/volume2.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/volume2.svg"),
    ),
    (
        "icons-glass/ai-sdk/x.svg",
        include_bytes!("../../../assets/icons-glass/ai-sdk/x.svg"),
    ),
    (
        "icons-glass/languages/bash.svg",
        include_bytes!("../../../assets/icons-glass/languages/bash.svg"),
    ),
    (
        "icons-glass/languages/c.svg",
        include_bytes!("../../../assets/icons-glass/languages/c.svg"),
    ),
    (
        "icons-glass/languages/cpp.svg",
        include_bytes!("../../../assets/icons-glass/languages/cpp.svg"),
    ),
    (
        "icons-glass/languages/css.svg",
        include_bytes!("../../../assets/icons-glass/languages/css.svg"),
    ),
    (
        "icons-glass/languages/go.svg",
        include_bytes!("../../../assets/icons-glass/languages/go.svg"),
    ),
    (
        "icons-glass/languages/html.svg",
        include_bytes!("../../../assets/icons-glass/languages/html.svg"),
    ),
    (
        "icons-glass/languages/javascript.svg",
        include_bytes!("../../../assets/icons-glass/languages/javascript.svg"),
    ),
    (
        "icons-glass/languages/json.svg",
        include_bytes!("../../../assets/icons-glass/languages/json.svg"),
    ),
    (
        "icons-glass/languages/python.svg",
        include_bytes!("../../../assets/icons-glass/languages/python.svg"),
    ),
    (
        "icons-glass/languages/rust.svg",
        include_bytes!("../../../assets/icons-glass/languages/rust.svg"),
    ),
    (
        "icons-glass/languages/toml.svg",
        include_bytes!("../../../assets/icons-glass/languages/toml.svg"),
    ),
    (
        "icons-glass/languages/typescript.svg",
        include_bytes!("../../../assets/icons-glass/languages/typescript.svg"),
    ),
    (
        "icons-glass/providers/claude.svg",
        include_bytes!("../../../assets/icons-glass/providers/claude.svg"),
    ),
    (
        "icons-glass/providers/cohere.svg",
        include_bytes!("../../../assets/icons-glass/providers/cohere.svg"),
    ),
    (
        "icons-glass/providers/custom.svg",
        include_bytes!("../../../assets/icons-glass/providers/custom.svg"),
    ),
    (
        "icons-glass/providers/deepseek.svg",
        include_bytes!("../../../assets/icons-glass/providers/deepseek.svg"),
    ),
    (
        "icons-glass/providers/ernie.svg",
        include_bytes!("../../../assets/icons-glass/providers/ernie.svg"),
    ),
    (
        "icons-glass/providers/gemini.svg",
        include_bytes!("../../../assets/icons-glass/providers/gemini.svg"),
    ),
    (
        "icons-glass/providers/gemma.svg",
        include_bytes!("../../../assets/icons-glass/providers/gemma.svg"),
    ),
    (
        "icons-glass/providers/glm.svg",
        include_bytes!("../../../assets/icons-glass/providers/glm.svg"),
    ),
    (
        "icons-glass/providers/gpt.svg",
        include_bytes!("../../../assets/icons-glass/providers/gpt.svg"),
    ),
    (
        "icons-glass/providers/grok.svg",
        include_bytes!("../../../assets/icons-glass/providers/grok.svg"),
    ),
    (
        "icons-glass/providers/llama.svg",
        include_bytes!("../../../assets/icons-glass/providers/llama.svg"),
    ),
    (
        "icons-glass/providers/minimax.svg",
        include_bytes!("../../../assets/icons-glass/providers/minimax.svg"),
    ),
    (
        "icons-glass/providers/mistral.svg",
        include_bytes!("../../../assets/icons-glass/providers/mistral.svg"),
    ),
    (
        "icons-glass/providers/nova.svg",
        include_bytes!("../../../assets/icons-glass/providers/nova.svg"),
    ),
    (
        "icons-glass/providers/perplexity.svg",
        include_bytes!("../../../assets/icons-glass/providers/perplexity.svg"),
    ),
    (
        "icons-glass/providers/phi.svg",
        include_bytes!("../../../assets/icons-glass/providers/phi.svg"),
    ),
    (
        "icons-glass/providers/qwen.svg",
        include_bytes!("../../../assets/icons-glass/providers/qwen.svg"),
    ),
    (
        "icons-glass/git/added_success.svg",
        include_bytes!("../../../assets/icons-glass/git/added_success.svg"),
    ),
    (
        "icons-glass/git/ahead_info.svg",
        include_bytes!("../../../assets/icons-glass/git/ahead_info.svg"),
    ),
    (
        "icons-glass/git/behind_warning.svg",
        include_bytes!("../../../assets/icons-glass/git/behind_warning.svg"),
    ),
    (
        "icons-glass/git/blame_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/blame_muted.svg"),
    ),
    (
        "icons-glass/git/blame_warning.svg",
        include_bytes!("../../../assets/icons-glass/git/blame_warning.svg"),
    ),
    (
        "icons-glass/git/branch_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/branch_muted.svg"),
    ),
    (
        "icons-glass/git/checkout_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/checkout_muted.svg"),
    ),
    (
        "icons-glass/git/clean_success.svg",
        include_bytes!("../../../assets/icons-glass/git/clean_success.svg"),
    ),
    (
        "icons-glass/git/clone_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/clone_muted.svg"),
    ),
    (
        "icons-glass/git/code-review_info.svg",
        include_bytes!("../../../assets/icons-glass/git/code-review_info.svg"),
    ),
    (
        "icons-glass/git/code-review_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/code-review_muted.svg"),
    ),
    (
        "icons-glass/git/commit_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/commit_muted.svg"),
    ),
    (
        "icons-glass/git/compare_error.svg",
        include_bytes!("../../../assets/icons-glass/git/compare_error.svg"),
    ),
    (
        "icons-glass/git/compare_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/compare_muted.svg"),
    ),
    (
        "icons-glass/git/compare_success.svg",
        include_bytes!("../../../assets/icons-glass/git/compare_success.svg"),
    ),
    (
        "icons-glass/git/conflict_warning.svg",
        include_bytes!("../../../assets/icons-glass/git/conflict_warning.svg"),
    ),
    (
        "icons-glass/git/deleted_error.svg",
        include_bytes!("../../../assets/icons-glass/git/deleted_error.svg"),
    ),
    (
        "icons-glass/git/fork_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/fork_muted.svg"),
    ),
    (
        "icons-glass/git/ignored_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/ignored_muted.svg"),
    ),
    (
        "icons-glass/git/inline-diff_error.svg",
        include_bytes!("../../../assets/icons-glass/git/inline-diff_error.svg"),
    ),
    (
        "icons-glass/git/inline-diff_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/inline-diff_muted.svg"),
    ),
    (
        "icons-glass/git/inline-diff_success.svg",
        include_bytes!("../../../assets/icons-glass/git/inline-diff_success.svg"),
    ),
    (
        "icons-glass/git/log_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/log_muted.svg"),
    ),
    (
        "icons-glass/git/merge_success.svg",
        include_bytes!("../../../assets/icons-glass/git/merge_success.svg"),
    ),
    (
        "icons-glass/git/modified_warning.svg",
        include_bytes!("../../../assets/icons-glass/git/modified_warning.svg"),
    ),
    (
        "icons-glass/git/pull-request_success.svg",
        include_bytes!("../../../assets/icons-glass/git/pull-request_success.svg"),
    ),
    (
        "icons-glass/git/pull_info.svg",
        include_bytes!("../../../assets/icons-glass/git/pull_info.svg"),
    ),
    (
        "icons-glass/git/push_success.svg",
        include_bytes!("../../../assets/icons-glass/git/push_success.svg"),
    ),
    (
        "icons-glass/git/rebase_ai.svg",
        include_bytes!("../../../assets/icons-glass/git/rebase_ai.svg"),
    ),
    (
        "icons-glass/git/rebase_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/rebase_muted.svg"),
    ),
    (
        "icons-glass/git/remote_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/remote_muted.svg"),
    ),
    (
        "icons-glass/git/staged_success.svg",
        include_bytes!("../../../assets/icons-glass/git/staged_success.svg"),
    ),
    (
        "icons-glass/git/staging_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/staging_muted.svg"),
    ),
    (
        "icons-glass/git/staging_success.svg",
        include_bytes!("../../../assets/icons-glass/git/staging_success.svg"),
    ),
    (
        "icons-glass/git/stash_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/stash_muted.svg"),
    ),
    (
        "icons-glass/git/tag_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/tag_muted.svg"),
    ),
    (
        "icons-glass/git/untracked_muted.svg",
        include_bytes!("../../../assets/icons-glass/git/untracked_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/agent_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/agent_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/api_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/api_info.svg"),
    ),
    (
        "icons-glass/dev-tools/breadcrumb_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/breadcrumb_info.svg"),
    ),
    (
        "icons-glass/dev-tools/breadcrumb_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/breadcrumb_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/cache_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/cache_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/chain_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/chain_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/ci-cd_success.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/ci-cd_success.svg"),
    ),
    (
        "icons-glass/dev-tools/container_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/container_info.svg"),
    ),
    (
        "icons-glass/dev-tools/context_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/context_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/debug_error.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/debug_error.svg"),
    ),
    (
        "icons-glass/dev-tools/deploy_success.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/deploy_success.svg"),
    ),
    (
        "icons-glass/dev-tools/embedding_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/embedding_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/environment_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/environment_info.svg"),
    ),
    (
        "icons-glass/dev-tools/environment_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/environment_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/extension_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/extension_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/file_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/file_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/find-replace_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/find-replace_info.svg"),
    ),
    (
        "icons-glass/dev-tools/fine-tune_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/fine-tune_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/folder_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/folder_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/function-call_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/function-call_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/function-call_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/function-call_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/guardrail_success.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/guardrail_success.svg"),
    ),
    (
        "icons-glass/dev-tools/health_error.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/health_error.svg"),
    ),
    (
        "icons-glass/dev-tools/keyboard_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/keyboard_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/logs_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/logs_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/logs_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/logs_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/memory_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/memory_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/minimap_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/minimap_info.svg"),
    ),
    (
        "icons-glass/dev-tools/minimap_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/minimap_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/model_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/model_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/monitor_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/monitor_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/monitor_success.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/monitor_success.svg"),
    ),
    (
        "icons-glass/dev-tools/orchestrator_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/orchestrator_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/orchestrator_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/orchestrator_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/palette_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/palette_info.svg"),
    ),
    (
        "icons-glass/dev-tools/palette_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/palette_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/pipeline_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/pipeline_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/pipeline_success.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/pipeline_success.svg"),
    ),
    (
        "icons-glass/dev-tools/pipeline_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/pipeline_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/prompt_ai.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/prompt_ai.svg"),
    ),
    (
        "icons-glass/dev-tools/queue_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/queue_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/rag_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/rag_info.svg"),
    ),
    (
        "icons-glass/dev-tools/rag_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/rag_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/rollback_error.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/rollback_error.svg"),
    ),
    (
        "icons-glass/dev-tools/scale_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/scale_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/scale_success.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/scale_success.svg"),
    ),
    (
        "icons-glass/dev-tools/search_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/search_info.svg"),
    ),
    (
        "icons-glass/dev-tools/secret_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/secret_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/settings_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/settings_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/sidebar_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/sidebar_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/snippet_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/snippet_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/snippet_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/snippet_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/split-view_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/split-view_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/streaming_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/streaming_info.svg"),
    ),
    (
        "icons-glass/dev-tools/tab_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/tab_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/terminal_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/terminal_muted.svg"),
    ),
    (
        "icons-glass/dev-tools/terminal_success.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/terminal_success.svg"),
    ),
    (
        "icons-glass/dev-tools/token_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/token_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/tool-use_warning.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/tool-use_warning.svg"),
    ),
    (
        "icons-glass/dev-tools/webhook_info.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/webhook_info.svg"),
    ),
    (
        "icons-glass/dev-tools/webhook_muted.svg",
        include_bytes!("../../../assets/icons-glass/dev-tools/webhook_muted.svg"),
    ),
];
